// <auto-generated />
namespace ShopEx01.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dataagain1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataagain1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904281544558_dataagain1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
